#!/usr/bin/env python3
"""Build a challenge-compliant Task 3 submission tree and optional zip.

This script converts predicted NIfTI files into the expected MRIxFields 2026
Task 3 layout:

    task3/
      T1W/<src>_to_<tgt>/pred/P_T1W_<tgt>_<id>.nii.gz
      T2W/<src>_to_<tgt>/pred/P_T2W_<tgt>_<id>.nii.gz
      T2FLAIR/<src>_to_<tgt>/pred/P_T2FLAIR_<tgt>_<id>.nii.gz

It supports both official filenames and legacy filenames generated by older
inference helpers.
"""

from __future__ import annotations

import argparse
import re
import sys
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import nibabel as nib
import numpy as np

from common.io import DOMAINS, MODALITIES

# Validation IDs required by the challenge for Task 3.
EXPECTED_IDS_BY_SOURCE: Dict[str, Tuple[str, str, str]] = {
    "0.1T": ("0001", "0002", "0003"),
    "1.5T": ("0004", "0005", "0008"),
    "3T": ("0010", "0011", "0012"),
    "5T": ("0013", "0014", "0015"),
    "7T": ("0016", "0017", "0018"),
}

PAIR_RE = re.compile(r"^([0-9.]+T)_to_([0-9.]+T)$")
OFFICIAL_RE = re.compile(r"^P_(T1W|T2W|T2FLAIR)_([0-9.]+T)_([0-9]{4})\.nii\.gz$")
LEGACY_RE = re.compile(
    r"^P_(T1W|T2W|T2FLAIR)_([0-9.]+T)_([0-9]{4})_(T1W|T2W|T2FLAIR)_([0-9.]+T)_.+\.nii\.gz$"
)


@dataclass
class Candidate:
    path: Path
    modality: str
    src_field: str
    tgt_field: str
    subject_id: str
    is_official: bool


def _parse_pair(pair_name: str) -> Optional[Tuple[str, str]]:
    m = PAIR_RE.match(pair_name)
    if m is None:
        return None
    return m.group(1), m.group(2)


def _parse_candidate(path: Path) -> Optional[Candidate]:
    name = path.name
    m1 = OFFICIAL_RE.match(name)
    if m1:
        return Candidate(
            path=path,
            modality=m1.group(1),
            src_field="",
            tgt_field=m1.group(2),
            subject_id=m1.group(3),
            is_official=True,
        )

    m2 = LEGACY_RE.match(name)
    if m2:
        return Candidate(
            path=path,
            modality=m2.group(1),
            src_field=m2.group(2),
            tgt_field=m2.group(5),
            subject_id=m2.group(3),
            is_official=False,
        )

    return None


def _find_task3_root(pred_root: Path) -> Path:
    # Accept either:
    # - <pred_root>/task3/<MOD>/<PAIR>/*.nii.gz
    # - <pred_root>/<MOD>/<PAIR>/*.nii.gz
    if (pred_root / "task3").is_dir():
        return pred_root / "task3"
    return pred_root


def _clip_and_save(
    src_file: Path,
    dst_file: Path,
    z_start: int,
    z_end: int,
    accept_preclipped: bool,
    expected_shape: Tuple[int, int, int],
) -> Tuple[int, int, int]:
    img = nib.load(str(src_file))
    data = img.get_fdata(dtype=np.float32)

    target_depth = z_end - z_start

    if data.ndim != 3:
        raise ValueError(f"Expected 3D NIfTI, got ndim={data.ndim} for {src_file}")

    if data.shape[2] >= z_end:
        clipped_img = img.slicer[:, :, z_start:z_end]
        clipped_data = clipped_img.get_fdata(dtype=np.float32)
        out_affine = clipped_img.affine
        out_header = clipped_img.header
    elif accept_preclipped and data.shape[2] == target_depth:
        # Keep as-is if volume is already clipped to 30 slices.
        clipped_data = data
        out_affine = img.affine
        out_header = img.header
    else:
        raise ValueError(
            f"Cannot apply z-clip [{z_start}:{z_end}] on shape {data.shape} for {src_file}"
        )

    clipped_data = np.clip(clipped_data, 0.0, 1.0).astype(np.float32)

    out_img = nib.Nifti1Image(clipped_data, out_affine, out_header)
    nib.save(out_img, str(dst_file))

    out_shape = tuple(int(v) for v in clipped_data.shape)
    if out_shape != expected_shape:
        raise ValueError(
            f"Invalid output shape {out_shape} for {dst_file}, expected {expected_shape}"
        )

    return out_shape


def _zip_task3(task3_dir: Path, zip_output: Path) -> None:
    zip_output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(zip_output, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for modality in MODALITIES:
            modality_dir = task3_dir / modality
            if not modality_dir.exists():
                continue
            for file_path in sorted(modality_dir.rglob("*.nii.gz")):
                arcname = str(file_path.relative_to(task3_dir))
                zf.write(file_path, arcname=arcname)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Build MRIxFields Task 3 submission tree")
    p.add_argument(
        "--pred-root",
        type=Path,
        required=True,
        help="Input prediction root, either <root>/task3/... or <root>/...",
    )
    p.add_argument(
        "--output-task3-dir",
        type=Path,
        default=Path("outputs/submission_ready/task3"),
        help="Output task3 directory to build (modalities at root)",
    )
    p.add_argument(
        "--modalities",
        nargs="+",
        default=MODALITIES,
        choices=MODALITIES,
        help="Modalities to process",
    )
    p.add_argument("--z-start", type=int, default=150, help="Axial clip start (inclusive)")
    p.add_argument("--z-end", type=int, default=180, help="Axial clip end (exclusive)")
    p.add_argument(
        "--accept-preclipped",
        action="store_true",
        help="Accept already-clipped volumes with depth (z-end-z-start)",
    )
    p.add_argument(
        "--strict",
        action="store_true",
        help="Fail if any (modality, pair) misses required IDs",
    )
    p.add_argument(
        "--clean",
        action="store_true",
        help="Remove existing output task3 directory before writing",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Print planned operations without writing files",
    )
    p.add_argument(
        "--zip-output",
        type=Path,
        default=None,
        help="Optional zip output path (example: ~/task3.zip)",
    )
    return p.parse_args()


def main() -> int:
    args = parse_args()

    if args.z_end <= args.z_start:
        print("ERROR: z-end must be greater than z-start", file=sys.stderr)
        return 2

    pred_root = _find_task3_root(args.pred_root)
    if not pred_root.exists():
        print(f"ERROR: input root not found: {pred_root}", file=sys.stderr)
        return 2

    target_depth = args.z_end - args.z_start
    expected_shape = (364, 436, target_depth)

    if args.clean and args.output_task3_dir.exists() and not args.dry_run:
        import shutil

        shutil.rmtree(args.output_task3_dir)

    total_written = 0
    total_pairs = 0
    failures: List[str] = []

    print(f"[INFO] Input task3 root: {pred_root}")
    print(f"[INFO] Output task3 dir: {args.output_task3_dir}")
    print(f"[INFO] z-clip: [{args.z_start}:{args.z_end}] -> depth={target_depth}")

    for modality in args.modalities:
        modality_dir = pred_root / modality
        if not modality_dir.exists():
            msg = f"Missing modality dir: {modality_dir}"
            print(f"[WARN] {msg}")
            failures.append(msg)
            continue

        for src in DOMAINS:
            for tgt in DOMAINS:
                if src == tgt:
                    continue
                total_pairs += 1
                pair = f"{src}_to_{tgt}"
                pair_dir = modality_dir / pair
                if not pair_dir.exists():
                    msg = f"Missing pair dir: {pair_dir}"
                    print(f"[WARN] {msg}")
                    failures.append(msg)
                    continue

                expected_ids = set(EXPECTED_IDS_BY_SOURCE[src])
                chosen: Dict[str, Candidate] = {}

                for f in sorted(pair_dir.glob("*.nii.gz")):
                    cand = _parse_candidate(f)
                    if cand is None:
                        continue
                    if cand.modality != modality:
                        continue
                    if cand.tgt_field != tgt:
                        continue
                    if cand.subject_id not in expected_ids:
                        continue
                    if not cand.is_official and cand.src_field and cand.src_field != src:
                        continue

                    prev = chosen.get(cand.subject_id)
                    if prev is None:
                        chosen[cand.subject_id] = cand
                    else:
                        # Prefer official filenames over legacy ones.
                        if cand.is_official and not prev.is_official:
                            chosen[cand.subject_id] = cand

                missing_ids = sorted(expected_ids - set(chosen.keys()))
                if missing_ids:
                    msg = f"{modality}/{pair}: missing IDs {missing_ids}"
                    print(f"[WARN] {msg}")
                    failures.append(msg)

                out_pred_dir = args.output_task3_dir / modality / pair / "pred"
                if not args.dry_run:
                    out_pred_dir.mkdir(parents=True, exist_ok=True)

                for sid in sorted(chosen.keys()):
                    src_file = chosen[sid].path
                    dst_file = out_pred_dir / f"P_{modality}_{tgt}_{sid}.nii.gz"

                    if args.dry_run:
                        print(f"[DRY] {src_file} -> {dst_file}")
                        continue

                    try:
                        _clip_and_save(
                            src_file=src_file,
                            dst_file=dst_file,
                            z_start=args.z_start,
                            z_end=args.z_end,
                            accept_preclipped=args.accept_preclipped,
                            expected_shape=expected_shape,
                        )
                        total_written += 1
                    except Exception as exc:
                        msg = f"Failed on {src_file}: {exc}"
                        print(f"[WARN] {msg}")
                        failures.append(msg)

    expected_total = len(args.modalities) * 20 * 3

    print("\n[SUMMARY]")
    print(f"Pairs visited: {total_pairs}")
    print(f"Files written: {total_written}")
    print(f"Expected files: {expected_total}")
    print(f"Warnings/failures: {len(failures)}")

    if args.strict and failures:
        print("\n[ERROR] Strict mode enabled and failures were found.", file=sys.stderr)
        return 1

    if args.zip_output is not None:
        if args.dry_run:
            print(f"[DRY] Would create zip: {args.zip_output.expanduser()}")
        else:
            zip_path = args.zip_output.expanduser()
            _zip_task3(args.output_task3_dir, zip_path)
            print(f"[INFO] Zip created: {zip_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
